apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::215737200395:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-IJVFXD70F5D
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::215737200395:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-26T21:32:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4259"
  uid: e0b2fb60-a7b7-4aea-8636-c01d814d377b
